// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8XFXSQuwyJVUq0ur8weKcnO3QHVIyoRo',
    appId: '1:437991889757:web:30af75c830adeec2a326b4',
    messagingSenderId: '437991889757',
    projectId: 'mobile-graduation-project',
    authDomain: 'mobile-graduation-project.firebaseapp.com',
    storageBucket: 'mobile-graduation-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQaydSVeeoMhSPYFwTYZDKzaYy0As9Sjw',
    appId: '1:437991889757:android:e3a86024dc7412a2a326b4',
    messagingSenderId: '437991889757',
    projectId: 'mobile-graduation-project',
    storageBucket: 'mobile-graduation-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTyyAwIAOFAcg-Jhh7L2OzWRs-nwVawqo',
    appId: '1:437991889757:ios:5f7fff5af072a381a326b4',
    messagingSenderId: '437991889757',
    projectId: 'mobile-graduation-project',
    storageBucket: 'mobile-graduation-project.firebasestorage.app',
    iosBundleId: 'com.test.flutterTestProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTyyAwIAOFAcg-Jhh7L2OzWRs-nwVawqo',
    appId: '1:437991889757:ios:5f7fff5af072a381a326b4',
    messagingSenderId: '437991889757',
    projectId: 'mobile-graduation-project',
    storageBucket: 'mobile-graduation-project.firebasestorage.app',
    iosBundleId: 'com.test.flutterTestProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8XFXSQuwyJVUq0ur8weKcnO3QHVIyoRo',
    appId: '1:437991889757:web:816a9bd8770bed96a326b4',
    messagingSenderId: '437991889757',
    projectId: 'mobile-graduation-project',
    authDomain: 'mobile-graduation-project.firebaseapp.com',
    storageBucket: 'mobile-graduation-project.firebasestorage.app',
  );
}
